<?php
/**
 * Blocking direct access to plugin
 */
defined('ABSPATH') or die('Are you crazy!');

/**
 * Equipeer class Metabox Equine General
 *
 * @class Metabox
 */
class Equipeer_Metabox extends Equipeer {
	
    /**
     * Constructor for the Equipeer_Metabox class
     *
     * Sets up all the appropriate hooks and actions
     */
    function __construct() {
        // Remove custom metabox equine (Taxonomies, Tags, Categories)
        add_action( 'admin_menu', array( $this, 'remove_metaboxes' ) );
		// Add Sticky bar in Equine post page (Admin)
		add_action('admin_enqueue_scripts', array( $this, 'admin_sticky_bar' ) );
	}

    /**
     * remove a custom taxonomy box from a custom post type edit screen
     *
     * @uses remove_meta_box()
     */
    public function remove_metaboxes() {
		
		// Remove AUTHOR metabox (Edit)
		//remove_meta_box( 'authordiv', $this->post_type, 'normal' );

		// Remove CUSTOM FIELDS metabox (Edit)
		// Only if not Admin
		$current_user = get_current_user_id();
		if ( $current_user != 1 )
			remove_meta_box( 'postcustom', $this->post_type, 'normal' );
		
		// Remove COMMENTS metabox (Edit)
		remove_meta_box( 'commentsdiv', $this->post_type, 'normal' );
		
		// Remove EXCERPT metabox (Edit)
		//remove_meta_box( 'postexcerpt' , $this->post_type, 'normal' );
		
		// Remove FEATURED IMAGE metabox (Edit)
		remove_meta_box( 'postimagediv' , $this->post_type, 'normal' );
		
		// Remove TAXONOMIES metabox (Edit)
        remove_meta_box( 'tagsdiv-equipeer_age', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_discipline', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_gender', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_group', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_level', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_potential', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_breed', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_color', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_size', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_equestrian_discipline', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_equestrian_level', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_rider_age', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_rider_behavior', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_rider_gender', $this->post_type, 'side' );
        remove_meta_box( 'tagsdiv-equipeer_rider_level', $this->post_type, 'side' );
    }
	
	/**
	 * Generated by the WordPress Meta Box generator
	 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
	 */
	function get_meta_value( $value ) {
		global $post;
	
		$field = get_post_meta( $post->ID, $value, true );
		if ( ! empty( $field ) ) {
			return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
		} else {
			return false;
		}
	}
	
	/**
	 * Add Sticky bar in ADMIN page (Equine add/edit)
	 *
	 * @return string
	 */
	function admin_sticky_bar($hook) {
		if ( ('post.php' == $hook || 'post-new.php' == $hook) && "equine" == get_post_type() ) {
			wp_enqueue_script('equipeer-sticky-bar', EQUIPEER_URL . 'assets/js/admin-toolbar.js');
			wp_enqueue_script('equipeer-form-i18n', EQUIPEER_URL . 'assets/js/admin-form-i18n.js');
			wp_enqueue_script('equipeer-form-label', EQUIPEER_URL . 'assets/js/admin-form-label.js');
		}
	}
	
}